name: project4-version-build

on:
  push:
    tags:
      - "v*.*.*"
  
jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Github repo setup
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag versioning
        id: tags
        uses: docker/metadata-action@v5
        with:
          images: pechuri/ceg3120-project-4
          tags:
            - type=semver,pattern={{version}}
            - type=semver,pattern={{major}}
            - type=semver,pattern={{major}}.{{minor}}
            - type=raw,value=latest

      - name: Push image to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.tags.outputs.labels }}
